- name: Install Postgres Service
  hosts: all
  become: yes

  tasks:
    - name: Create necessary directory for Postgres persistent data
      ansible.builtin.file:
        path: /etc/quay-install/pg-data
        state: directory
        recurse: yes
        owner: root
        group: root
        mode: "0755"

    - name: Set permissions on data directory
      ansible.posix.acl:
        path: /etc/quay-install/pg-data
        entry: u:26:-wx
        state: present

    - name: Copy Postgres systemd service file
      template: src=../templates/postgres.service dest=/etc/systemd/system/quay-postgres.service

    - name: Pull Postgres image
        containers.podman.podman_image:
        name: docker.io/centos/postgresql-10-centos8

    - name: Start Postgres service
      systemd:
        name: quay-postgres.service
        enabled: yes
        daemon_reload: yes
        state: started
