- name: Waiting up to 3 minutes for Quay to become alive at https://{{ inventory_hostname.split("@")[1] }}/health/instance
  uri:
    url: "https://localhost/health/instance"
    method: GET
    validate_certs: no
  register: result
  until: result.status == 200
  retries: 10
  delay: 30
