---
version: 1

# build_arg_defaults:
#   EE_BASE_IMAGE: quay.io/aap/ansible-automation-platform-20-ee-minimal-rhel8:latest

dependencies:
  galaxy: requirements.yml
  python: requirements.txt

additional_build_steps:
  append:
    - COPY app /runner
